// <auto-generated />
using System;
using System.Collections.Generic;
using Budget.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Budget.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20261003114610_AddExpenseDescription")]
    partial class AddExpenseDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Budget.Domain.Aggregates.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique();

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.BudgetAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_person_id");

                    b.Property<int>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("revision");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId", "Visibility", "OwnerPersonId");

                    b.ToTable("budget_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_accounts_owner_matches_visibility", "(visibility = 'Personal') = (owner_person_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("added_by_display_name");

                    b.Property<Guid>("AddedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_person_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_account_id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("description");

                    b.Property<string>("FundingSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("funding_source");

                    b.Property<bool>("IsVoided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_voided");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<string>("PaidByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("paid_by_display_name");

                    b.Property<Guid?>("PaidByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_person_id");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.HasKey("Id");

                    b.HasIndex("BudgetAccountId", "BudgetId");

                    b.HasIndex("BudgetId", "OccurredOn", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_expenses_budget_date_id");

                    b.HasIndex("BudgetId", "Category", "Amount", "OccurredOn")
                        .HasDatabaseName("ix_expenses_duplicate_lookup");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_amount_range", "amount > 0 AND amount <= 9999999999.99");

                            t.HasCheckConstraint("ck_expenses_payer_matches_funding", "(funding_source = 'HouseholdFunds') = (paid_by_person_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.MonthlyLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_account_id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateOnly>("MonthStart")
                        .HasColumnType("date")
                        .HasColumnName("month_start");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BudgetAccountId", "BudgetId");

                    b.HasIndex("BudgetAccountId", "MonthStart")
                        .IsUnique()
                        .HasDatabaseName("ux_monthly_limits_account_month");

                    b.ToTable("monthly_limits", null, t =>
                        {
                            t.HasCheckConstraint("ck_monthly_limits_amount_range", "amount >= 0 AND amount <= 9999999999.99");

                            t.HasCheckConstraint("ck_monthly_limits_month_start", "EXTRACT(DAY FROM month_start) = 1");
                        });
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("added_by_display_name");

                    b.Property<Guid>("AddedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_person_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_display_name");

                    b.Property<Guid>("FromPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_person_id");

                    b.Property<bool>("IsVoided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_voided");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date")
                        .HasColumnName("paid_on");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("ToDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to_display_name");

                    b.Property<Guid>("ToPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_person_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("void_reason");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<string>("VoidedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("voided_by_display_name");

                    b.Property<Guid?>("VoidedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by_person_id");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId", "PaidOn")
                        .HasDatabaseName("ix_settlements_budget_date");

                    b.HasIndex("BudgetId", "AddedByPersonId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_settlements_request_identity");

                    b.ToTable("settlements", null, t =>
                        {
                            t.HasCheckConstraint("ck_settlements_amount_range", "amount > 0 AND amount <= 9999999999.99");

                            t.HasCheckConstraint("ck_settlements_distinct_people", "from_person_id <> to_person_id");
                        });
                });

            modelBuilder.Entity("Budget.Domain.Entities.ExpenseRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorDisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("actor_display_name");

                    b.Property<Guid>("ActorPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_person_id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Request", "Budget.Domain.Entities.ExpenseRevision.Request#ExpenseRequest", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("AccountId");

                            b1.Property<string>("Action")
                                .IsRequired();

                            b1.Property<string>("Amount")
                                .IsRequired();

                            b1.Property<int>("Category");

                            b1.Property<string>("Description");

                            b1.Property<int?>("ExpectedRevision");

                            b1.Property<Guid?>("ExpenseId");

                            b1.Property<int>("FundingSource");

                            b1.Property<DateOnly>("OccurredOn");

                            b1.Property<Guid?>("PaidByPersonId");

                            b1.PrimitiveCollection<string>("ParticipantIds")
                                .IsRequired();

                            b1.Property<string>("Reason");

                            b1
                                .ToJson("request")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Snapshot", "Budget.Domain.Entities.ExpenseRevision.Snapshot#ExpenseSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddedByDisplayName")
                                .IsRequired();

                            b1.Property<Guid>("AddedByPersonId");

                            b1.Property<decimal>("Amount");

                            b1.Property<int>("Category");

                            b1.Property<string>("Description");

                            b1.Property<int>("FundingSource");

                            b1.Property<bool>("IsVoided");

                            b1.Property<DateOnly>("OccurredOn");

                            b1.Property<string>("PaidByDisplayName");

                            b1.Property<Guid?>("PaidByPersonId");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Shares", "Budget.Domain.Entities.ExpenseRevision.Snapshot#ExpenseSnapshot.Shares#ShareSnapshot", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("PersonDisplayName")
                                        .IsRequired();

                                    b2.Property<Guid>("PersonId");
                                });

                            b1
                                .ToJson("snapshot")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex("BudgetId", "ActorPersonId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_expense_revisions_request_identity");

                    b.ToTable("expense_revisions", (string)null);
                });

            modelBuilder.Entity("Shared.Infrastructure.Messaging.Ef.Inbox.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("event_type");

                    b.HasKey("EventId");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Shared.Infrastructure.Messaging.Ef.Outbox.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("RetriedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retried_at");

                    b.Property<Guid?>("RetryOf")
                        .HasColumnType("uuid")
                        .HasColumnName("retry_of");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("\"processed_at\" IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.BudgetAccount", b =>
                {
                    b.HasOne("Budget.Domain.Aggregates.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.Expense", b =>
                {
                    b.HasOne("Budget.Domain.Aggregates.BudgetAccount", null)
                        .WithMany()
                        .HasForeignKey("BudgetAccountId", "BudgetId")
                        .HasPrincipalKey("Id", "BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Budget.Domain.Entities.ExpenseShare", "Shares", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid")
                                .HasColumnName("expense_id");

                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("person_id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("PersonDisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("person_display_name");

                            b1.HasKey("ExpenseId", "PersonId");

                            b1.HasIndex("PersonId");

                            b1.ToTable("expense_shares", null, t =>
                                {
                                    t.HasCheckConstraint("ck_expense_shares_amount", "amount >= 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.MonthlyLimit", b =>
                {
                    b.HasOne("Budget.Domain.Aggregates.BudgetAccount", null)
                        .WithMany()
                        .HasForeignKey("BudgetAccountId", "BudgetId")
                        .HasPrincipalKey("Id", "BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.Settlement", b =>
                {
                    b.HasOne("Budget.Domain.Aggregates.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Budget.Domain.Entities.ExpenseRevision", b =>
                {
                    b.HasOne("Budget.Domain.Aggregates.Expense", null)
                        .WithMany("Revisions")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Budget.Domain.Aggregates.Expense", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
