<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj" />
    <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
    <ProjectReference Include="..\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
  </ItemGroup>

</Project>
