// <auto-generated />
using System;
using DietPlanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DietPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(DietPlannerDbContext))]
    [Migration("20260926113332_ReminderSettingsLocalTimes")]
    partial class ReminderSettingsLocalTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.DietReminderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("GoalAlertsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("goal_alerts_enabled");

                    b.Property<int>("MealMissedGraceMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("meal_missed_grace_minutes");

                    b.Property<int>("MealReminderLeadTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("meal_reminder_lead_time_minutes");

                    b.Property<bool>("MealRemindersEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("meal_reminders_enabled");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WaterReminderIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("water_reminder_interval_minutes");

                    b.Property<bool>("WaterRemindersEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("water_reminders_enabled");

                    b.Property<TimeOnly>("WaterWindowEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("water_window_end");

                    b.Property<TimeOnly>("WaterWindowStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("water_window_start");

                    b.Property<int>("WeeklySummaryDayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_summary_day_of_week");

                    b.Property<bool>("WeeklySummaryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("weekly_summary_enabled");

                    b.Property<TimeOnly>("WeeklySummaryTimeOfDay")
                        .HasColumnType("time without time zone")
                        .HasColumnName("weekly_summary_time_of_day");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_diet_reminder_settings_person");

                    b.ToTable("diet_reminder_settings", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.HydrationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyWaterTargetMl")
                        .HasColumnType("integer")
                        .HasColumnName("daily_water_target_ml");

                    b.Property<int>("GlassSizeMl")
                        .HasColumnType("integer")
                        .HasColumnName("glass_size_ml");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<bool>("TrackWaterIntake")
                        .HasColumnType("boolean")
                        .HasColumnName("track_water_intake");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_hydration_configs_person");

                    b.ToTable("hydration_configs", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.MealEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActualRecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("actual_recipe_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("MealSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_slot_id");

                    b.Property<TimeOnly?>("MealTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("meal_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int?>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<decimal>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("servings");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Planned")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ActualRecipeId")
                        .HasDatabaseName("idx_meal_entries_actual_recipe");

                    b.HasIndex("MealSlotId")
                        .HasDatabaseName("idx_meal_entries_meal_slot");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("idx_meal_entries_recipe");

                    b.HasIndex("PersonId", "Date")
                        .HasDatabaseName("idx_meal_entries_person_date");

                    b.ToTable("meal_entries", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.MealScheduleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_meal_schedule_configs_person");

                    b.ToTable("meal_schedule_configs", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_unit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("DensityGramsPerMl")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("density_grams_per_ml");

                    b.Property<decimal?>("GramPerPiece")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gram_per_piece");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_products_created_by");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_products_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("servings");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_recipes_created_by");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_recipes_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CarbsGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("carbs_grams");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DailyCalorieTarget")
                        .HasColumnType("integer")
                        .HasColumnName("daily_calorie_target");

                    b.Property<decimal?>("FatGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_grams");

                    b.Property<decimal?>("FiberGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("fiber_grams");

                    b.Property<DateTime?>("MilestoneAchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("milestone_achieved_at");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<decimal?>("ProteinGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("protein_grams");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("target_weight_kg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_goals_person");

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("activity_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("current_weight_kg");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Gender")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("height_cm");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("target_weight_kg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_profiles_person");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.WaterIntake", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountMl")
                        .HasColumnType("integer")
                        .HasColumnName("amount_ml");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Date")
                        .HasDatabaseName("idx_water_intakes_person_date");

                    b.ToTable("water_intakes", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.WeightEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Date")
                        .IsUnique()
                        .HasDatabaseName("idx_weight_entries_person_date");

                    b.ToTable("weight_entries", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Entities.MealEntryActualProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<Guid>("meal_entry_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_meal_entry_actual_products_product");

                    b.HasIndex("meal_entry_id");

                    b.ToTable("meal_entry_actual_products", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Entities.MealSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("DefaultTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("default_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("meal_schedule_config_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("meal_schedule_config_id");

                    b.ToTable("meal_slots", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_recipe_ingredients_product");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("idx_recipe_ingredients_recipe");

                    b.HasIndex("RecipeId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("unique_recipe_product");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Ledgers.SentMealReminder", b =>
                {
                    b.Property<Guid>("MealEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_entry_id");

                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("MealEntryId", "Kind");

                    b.ToTable("sent_meal_reminders", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Ledgers.WaterReminderState", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("LastWaterReminderAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_water_reminder_at");

                    b.HasKey("PersonId");

                    b.ToTable("water_reminder_state", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Ledgers.WeeklySummaryState", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("LastWeeklySummaryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_weekly_summary_at");

                    b.HasKey("PersonId");

                    b.ToTable("weekly_summary_state", (string)null);
                });

            modelBuilder.Entity("Shared.Infrastructure.Messaging.Ef.Outbox.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("\"processed_at\" IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.MealEntry", b =>
                {
                    b.HasOne("DietPlanner.Domain.Aggregates.Recipe", null)
                        .WithMany()
                        .HasForeignKey("ActualRecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DietPlanner.Domain.Entities.MealSlot", null)
                        .WithMany()
                        .HasForeignKey("MealSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DietPlanner.Domain.Aggregates.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.Product", b =>
                {
                    b.OwnsOne("DietPlanner.Domain.ValueObjects.NutritionPer100g", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Calories")
                                .HasColumnType("numeric")
                                .HasColumnName("calories_per_100g");

                            b1.Property<decimal?>("Carbs")
                                .HasColumnType("numeric")
                                .HasColumnName("carbs_per_100g");

                            b1.Property<decimal?>("Fat")
                                .HasColumnType("numeric")
                                .HasColumnName("fat_per_100g");

                            b1.Property<decimal?>("Fiber")
                                .HasColumnType("numeric")
                                .HasColumnName("fiber_per_100g");

                            b1.Property<decimal?>("Protein")
                                .HasColumnType("numeric")
                                .HasColumnName("protein_per_100g");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("DietPlanner.Domain.Entities.MealEntryActualProduct", b =>
                {
                    b.HasOne("DietPlanner.Domain.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DietPlanner.Domain.Aggregates.MealEntry", null)
                        .WithMany("ActualProducts")
                        .HasForeignKey("meal_entry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietPlanner.Domain.Entities.MealSlot", b =>
                {
                    b.HasOne("DietPlanner.Domain.Aggregates.MealScheduleConfig", null)
                        .WithMany("Slots")
                        .HasForeignKey("meal_schedule_config_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DietPlanner.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("DietPlanner.Domain.Aggregates.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DietPlanner.Domain.Aggregates.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.MealEntry", b =>
                {
                    b.Navigation("ActualProducts");
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.MealScheduleConfig", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DietPlanner.Domain.Aggregates.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
