<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DietPlanner.Application\DietPlanner.Application.csproj" />
    <ProjectReference Include="..\DietPlanner.Contracts\DietPlanner.Contracts.csproj" />
    <ProjectReference Include="..\DietPlanner.Infrastructure\DietPlanner.Infrastructure.csproj" />
  </ItemGroup>

</Project>
