// <auto-generated />
using System;
using DietPlanner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DietPlanner.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310064034_RemoveDietPlanAddUserIdToMealEntry")]
    partial class RemoveDietPlanAddUserIdToMealEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DietPlanner.Api.Domain.MealEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly?>("MealTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("meal_time");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("meal_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int?>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<decimal>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("servings");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("idx_meal_entries_recipe");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("idx_meal_entries_user_date");

                    b.ToTable("meal_entries", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CaloriesPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("calories_per_100g");

                    b.Property<decimal?>("CarbsPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("carbs_per_100g");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_unit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("DensityGramsPerMl")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("density_grams_per_ml");

                    b.Property<decimal?>("FatPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_per_100g");

                    b.Property<decimal?>("FiberPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("fiber_per_100g");

                    b.Property<decimal?>("GramPerPiece")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gram_per_piece");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("ProteinPer100g")
                        .HasColumnType("numeric")
                        .HasColumnName("protein_per_100g");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_products_created_by");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_products_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("servings");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_recipes_created_by");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_recipes_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_recipe_ingredients_product");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("idx_recipe_ingredients_recipe");

                    b.HasIndex("RecipeId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("unique_recipe_product");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CarbsGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("carbs_grams");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DailyCalorieTarget")
                        .HasColumnType("integer")
                        .HasColumnName("daily_calorie_target");

                    b.Property<decimal?>("FatGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("fat_grams");

                    b.Property<decimal?>("FiberGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("fiber_grams");

                    b.Property<decimal?>("ProteinGrams")
                        .HasColumnType("numeric")
                        .HasColumnName("protein_grams");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_goals_user");

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.MealEntry", b =>
                {
                    b.HasOne("DietPlanner.Api.Domain.Recipe", "Recipe")
                        .WithMany("MealEntries")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("DietPlanner.Api.Domain.Product", "Product")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DietPlanner.Api.Domain.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.Product", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DietPlanner.Api.Domain.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("MealEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
